# Generated by Django 4.2.7 on 2025-12-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('admin', 'Administrator'), ('super_admin', 'Super Administrator'), ('principal', 'Principal'), ('headmaster', 'Headmaster'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('counselor', 'Counselor'), ('supervisor', 'Supervisor'), ('vice_principal', 'Vice Principal'), ('department_head', 'Department Head'), ('clerk', 'Clerk'), ('hr', 'Human Resources'), ('it_staff', 'IT Staff'), ('lab_assistant', 'Lab Assistant')], db_index=True, max_length=20),
        ),
    ]
